DEFINE VARIABLE cdirName AS CHARACTER   NO-UNDO.

ASSIGN cdirName =  "C:\Testing\".

FILE-INFO:FILENAME = cdirName.

IF FILE-INFO:FULL-PATHNAME = ? THEN
DO:
    MESSAGE "Dir does not exit"
        VIEW-AS ALERT-BOX INFORMATION BUTTONS OK.
    RETURN.
END.

IF FILE-INFO:FILE-TYPE  THEN



