DEFINE SHARED VARIABLE XCodeKey         AS CHARACTER NO-UNDO.
DEFINE SHARED VARIABLE SourceFileFull   AS CHARACTER NO-UNDO.
DEFINE SHARED VARIABLE CodeListFile     AS CHARACTER NO-UNDO.
DEFINE SHARED VARIABLE DebugListFile    AS CHARACTER NO-UNDO.
DEFINE SHARED VARIABLE RCodePath        AS CHARACTER NO-UNDO.
COMPILE VALUE(SourceFileFull) SAVE INTO VALUE(RCodePath) NO-ERROR.
